services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: login
      MYSQL_PASSWORD: password
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    init_command: "mysql -u root -proot_password < /init.sql"
    volumes:
      - openstack_volume:/var/lib/mysql
    ports:
      - "80:443"

volumes:
  openstack_volume:
    driver: openstack
    driver_opts:
      share_name: openstack_volume
