version: '3'

services:
  web:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
    environment:
      PHP_INI_DIR: /usr/local/etc/php/
      PHP_EXTRA_CONFIGURE_ARGS: --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: '0'
      PHP_OPCACHE_MAX_ACCELERATED_FILES: '10000'
      PHP_OPCACHE_MEMORY_CONSUMPTION: '192'
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: '10'
    ports:
      - "22:22"

volumes:
  test-vol1:
